from __future__ import annotations

import json
from pathlib import Path

from wallee_v6.packs.prusa_core_one_plus.bgcode_decode import BgcodeDecodeError, decode_bgcode_text, normalize_prusa_print_text
from wallee_v6.packs.prusa_core_one_plus.job_notebook import (
    active_notes_to_jsonable,
    build_job_notebook,
    CURRENT_NOTEBOOK_SCHEMA_VERSION,
    CURRENT_NOTEBOOK_PARSER_VERSION,
    load_persisted_notebook,
    notebook_to_jsonable,
    persist_job_notebook,
)
from wallee_v6.packs.prusa_core_one_plus.types import PrintableFile


_SAMPLE_GCODE = """; generated by PrusaSlicer
; filament_type = PLA
; layer_height = 0.20
M104 S215
M140 S60
;LAYER_CHANGE
;LAYER:0
;Z:0.20
;TYPE:Perimeter
G1 X0 Y0 E1
;TYPE:Bridge infill
G1 X10 Y10 E2
;LAYER_CHANGE
;LAYER:1
;Z:0.40
;TYPE:Internal infill
G1 X20 Y20 E3
;LAYER_CHANGE
;LAYER:2
;Z:0.60
;TYPE:Bridge infill
G1 X30 Y30 E4
"""

_STRINGING_TOWER_GCODE = """; generated by PrusaSlicer
; filament_type = PLA
; layer_height = 0.16
M104 S220
M140 S55
;LAYER_CHANGE
;LAYER:0
;Z:0.16
;TYPE:Perimeter
G1 X0 Y0 E1
;TYPE:Bridge infill
G1 X10 Y10 E2
;LAYER_CHANGE
;LAYER:1
;Z:0.32
;TYPE:Perimeter
G1 X1 Y1 E3
;TYPE:Bridge infill
G1 X11 Y11 E4
;LAYER_CHANGE
;LAYER:2
;Z:0.48
;TYPE:Perimeter
G1 X2 Y2 E5
;TYPE:Perimeter
G1 X12 Y12 E6
"""

_PLANNING_FACTS_GCODE = """; generated by PrusaSlicer
; filament_type = PLA
; layer_height = 0.20
; estimated_printing_time = 10m 0s
M204 P800 T1500 R300
M83
;LAYER_CHANGE
;LAYER:0
;Z:0.20
G1 X0 Y0 F6000
G1 X4 Y0 E0.5
G1 E-0.8
G0 X50 Y0 F9000
G1 E0.8
G1 X54 Y0 E0.5
;LAYER_CHANGE
;LAYER:1
;Z:0.40
G1 X0 Y2 F6000
G1 X4 Y2 E0.5
G1 E-0.8
G0 X50 Y2 F9000
G1 E0.8
G1 X54 Y2 E0.5
;LAYER_CHANGE
;LAYER:2
;Z:0.60
G1 X0 Y4 F6000
G1 X4 Y4 E0.5
G1 E-0.8
G0 X50 Y4 F9000
G1 E0.8
G1 X54 Y4 E0.5
"""


def _fixture_text(name: str) -> str:
    repo_root = Path(__file__).resolve().parents[1]
    candidates = [
        repo_root / "tests" / "fixtures" / name,
        repo_root.parent / "wallee_v6_fff_prusa_addon" / "tests" / "fixtures" / name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate.read_text(encoding="utf-8", errors="replace")
    raise FileNotFoundError(f"fixture not found: {name}")


def _bgcode_fixture_bytes(name: str) -> bytes:
    base = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "prusa_bgcode"
    return (base / name).read_bytes()


def test_build_job_notebook_creates_grounded_sections_and_notes(tmp_path):
    notes_path = tmp_path / "notes"
    printable = PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode", size_bytes=len(_SAMPLE_GCODE))
    baseline = build_job_notebook(
        printable=printable,
        file_info={"metadata": {"filament_type": "PLA", "layer_height": 0.2, "bed_temperature": 60}},
        file_text=_SAMPLE_GCODE,
    )
    assert baseline is not None

    (notes_path / f"{baseline.job_hash}.notes.json").parent.mkdir(parents=True, exist_ok=True)
    (notes_path / f"{baseline.job_hash}.notes.json").write_text(
        json.dumps(
            {
                "global_notes": [
                    {
                        "note_id": "global_operator",
                        "scope": "global",
                        "kind": "watchpoint",
                        "text": "Operator note: watch the bridge region after 60% progress.",
                        "priority": 15,
                    }
                ],
                "local_notes": [
                    {
                        "note_id": "local_bridge_focus",
                        "scope": "local",
                        "kind": "watchpoint",
                        "text": "Bridge focus region.",
                        "section_ids": ["sec_0003"],
                        "priority": 35,
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    notebook = build_job_notebook(
        printable=printable,
        file_info={"metadata": {"filament_type": "PLA", "layer_height": 0.2, "bed_temperature": 60}},
        file_text=_SAMPLE_GCODE,
        notes_dir=notes_path,
    )
    assert notebook is not None
    assert notebook.material == "PLA"
    assert notebook.nozzle_target_c == 215
    assert notebook.bed_target_c == 60
    assert len(notebook.sections) == 3
    assert notebook.sections[0].layer_start == 0
    assert notebook.sections[2].layer_start == 2
    assert notebook.sections[2].z_min_mm == 0.6
    assert notebook.active_section(90.0).section_id == "sec_0003"

    active_notes = notebook.active_notes(90.0)
    texts = [note.text for note in active_notes]
    assert any("Operator note" in text for text in texts)
    assert any("Bridge focus region" in text for text in texts)
    assert any("Bridge-heavy region" in text for text in texts)

    payload = notebook_to_jsonable(notebook)
    assert sorted(payload.keys()) == [
        "baselines",
        "build",
        "global_notes",
        "job",
        "local_notes",
        "notebook_id",
        "printer_family",
        "schema_version",
        "sections",
    ]
    assert payload["schema_version"] == CURRENT_NOTEBOOK_SCHEMA_VERSION
    assert payload["printer_family"] == "prusa_core_one_plus"
    assert payload["job"]["job_hash"] == notebook.job_hash
    assert payload["baselines"]["speed_pct_default"] == 100.0
    assert all(note["section_ids"] == [] for note in payload["global_notes"])
    assert all(note["section_ids"] for note in payload["local_notes"])
    assert payload["sections"][2]["section_id"] == "sec_0003"
    assert payload["sections"][2]["progress_start_pct"] > payload["sections"][1]["progress_start_pct"]
    assert payload["sections"][2]["progress_end_pct"] == 100.0
    assert payload["local_notes"][-1]["note_id"] == "local_bridge_focus"

    active = notebook.select_active_notes(90.0, lifecycle="PRINTING", job_active=True)
    active_payload = active_notes_to_jsonable(active)
    assert active_payload["schema_version"] == "1.0"
    assert len(active_payload["global_notes"]) <= 4
    assert len(active_payload["local_notes"]) <= 6
    assert set(active_payload["family_hints"].keys()) == {
        "speed",
        "flow",
        "nozzle",
        "bed",
        "pressure_advance",
        "accel",
    }


def test_active_notes_summary_limits_output_length():
    notebook = build_job_notebook(
        printable=PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode"),
        file_info=None,
        file_text=_SAMPLE_GCODE,
    )
    assert notebook is not None

    summary = notebook.active_notes_summary(75.0, limit=2)
    assert summary is not None
    assert len(summary) <= 320
    assert "|" in summary or summary.endswith(".")


def test_gcode_planning_facts_are_derived_and_exposed_in_active_payload():
    notebook = build_job_notebook(
        printable=PrintableFile(path="/usb/PRINTS/STRINGING_FACTS.GCODE", display_name="stringing_facts.gcode"),
        file_info=None,
        file_text=_PLANNING_FACTS_GCODE,
    )
    assert notebook is not None
    assert notebook.baselines.estimated_print_time_s == 600.0
    assert len(notebook.sections) == 3

    active_section = notebook.sections[1]
    facts = active_section.gcode_facts
    assert facts.long_travel_count >= 2
    assert facts.long_travel_distance_mm > 90.0
    assert facts.retraction_count == 1
    assert facts.restart_count == 1
    assert facts.travel_to_extrusion_ratio is not None
    assert facts.travel_to_extrusion_ratio > 10.0
    assert facts.active_m204_p_mm_s2 == 800.0
    assert facts.active_m204_t_mm_s2 == 1500.0
    assert facts.active_m204_r_mm_s2 == 300.0
    assert facts.extrusion_cluster_count >= 2
    assert any("long_travel" in window.reason_tags for window in facts.snapshot_windows)
    assert all(window.gcode_line_start is not None for window in facts.snapshot_windows)
    assert "stringing_test_geometry" in active_section.tags

    progress = (active_section.progress_start_pct + active_section.progress_end_pct) / 2.0
    active = notebook.select_active_notes(progress, lifecycle="PRINTING", job_active=True)
    active_payload = active_notes_to_jsonable(active)
    planner_facts = active_payload["planner_facts"]
    assert planner_facts["geometry"]["repeated_tower_or_stringing_test"] is True
    assert active_section.section_id in planner_facts["geometry"]["section_ids"]
    assert planner_facts["active_section"]["section_id"] == active_section.section_id
    assert planner_facts["active_section"]["remaining_progress_pct"] > 0
    assert planner_facts["active_section"]["remaining_time_s"] > 0
    assert planner_facts["active_section"]["gcode_facts"]["retraction_count"] == 1
    assert any(note["note_id"] == "global_stringing_geometry" for note in active_payload["global_notes"])


def test_select_active_notes_truncates_compact_payload_deterministically(tmp_path):
    printable = PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode", size_bytes=len(_SAMPLE_GCODE))
    baseline = build_job_notebook(printable=printable, file_info=None, file_text=_SAMPLE_GCODE)
    assert baseline is not None

    notes_dir = tmp_path / "notes"
    notes_dir.mkdir(parents=True, exist_ok=True)
    local_section_id = baseline.sections[-1].section_id
    (notes_dir / f"{baseline.job_hash}.notes.json").write_text(
        json.dumps(
            {
                "global_notes": [
                    {
                        "note_id": f"global_{index}",
                        "scope": "global",
                        "title": f"Global {index}",
                        "text": f"Global note {index}",
                        "confidence": "high" if index < 3 else "medium",
                        "priority": 10 + index,
                    }
                    for index in range(7)
                ],
                "local_notes": [
                    {
                        "note_id": f"local_{index}",
                        "scope": "local",
                        "title": f"Local {index}",
                        "text": f"Local note {index}",
                        "section_ids": [local_section_id],
                        "confidence": "high" if index < 4 else "medium",
                        "priority": 20 + index,
                    }
                    for index in range(9)
                ],
            }
        ),
        encoding="utf-8",
    )

    notebook = build_job_notebook(
        printable=printable,
        file_info=None,
        file_text=_SAMPLE_GCODE,
        notes_dir=notes_dir,
    )
    assert notebook is not None

    active = notebook.select_active_notes(90.0, lifecycle="PRINTING", job_active=True)
    assert len(active.global_notes) == 4
    assert len(active.local_notes) == 6
    assert [note.note_id for note in active.global_notes] == ["global_0", "global_material", "global_1", "global_layer_height"]
    assert [note.note_id for note in active.local_notes] == ["local_0", "local_1", "local_2", "local_3", "local_4", "local_5"]


def test_job_hash_is_stable_for_same_file_and_ignores_transient_input_availability():
    printable = PrintableFile(
        path="/usb/PRINTS/BENCHY~2.BGC",
        display_name="Benchy_Rules_0.4n_0.2mm_PLA_COREONE_14m.bgcode",
        size_bytes=123456,
        modified_ts=1711800000,
    )
    text = _fixture_text("sample_prusa.gcode")
    with_text = build_job_notebook(
        printable=printable,
        file_info={"metadata": {"filament_type": "PLA", "layer_height": 0.2}},
        file_text=text,
    )
    without_text = build_job_notebook(
        printable=printable,
        file_info={"metadata": {"filament_type": "PLA", "layer_height": 0.2}},
        file_text=None,
    )
    repeated = build_job_notebook(
        printable=printable,
        file_info={"metadata": {"filament_type": "PLA", "layer_height": 0.2}},
        file_text=text,
    )

    assert with_text is not None
    assert without_text is not None
    assert repeated is not None
    assert with_text.job_hash == without_text.job_hash == repeated.job_hash


def test_job_hash_differs_for_different_files():
    benchy = build_job_notebook(
        printable=PrintableFile(
            path="/usb/PRINTS/BENCHY~2.BGC",
            display_name="Benchy_Rules_0.4n_0.2mm_PLA_COREONE_14m.bgcode",
            size_bytes=123456,
        ),
        file_info=None,
        file_text=_fixture_text("sample_prusa.gcode"),
    )
    stringing = build_job_notebook(
        printable=PrintableFile(
            path="/usb/PRINTS/STRINGING~1.BGC",
            display_name="Stringing_v2_Test_mini_0.4n_0.2mm_PLA_COREONE_7m.bgcode",
            size_bytes=654321,
        ),
        file_info=None,
        file_text=_STRINGING_TOWER_GCODE,
    )

    assert benchy is not None
    assert stringing is not None
    assert benchy.job_hash != stringing.job_hash


def test_load_persisted_notebook_rejects_stale_schema(tmp_path):
    notebook = build_job_notebook(
        printable=PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode"),
        file_info=None,
        file_text=_SAMPLE_GCODE,
    )
    assert notebook is not None
    path = tmp_path / f"{notebook.job_hash}.notebook.json"
    payload = notebook_to_jsonable(notebook)
    payload.pop("schema_version")
    path.write_text(json.dumps(payload), encoding="utf-8")

    try:
        load_persisted_notebook(path)
    except ValueError as exc:
        assert "keys mismatch" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected stale notebook schema to be rejected")


def test_persisted_notebook_round_trips_current_schema(tmp_path):
    notebook = build_job_notebook(
        printable=PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode"),
        file_info=None,
        file_text=_SAMPLE_GCODE,
    )
    assert notebook is not None
    path = tmp_path / f"{notebook.job_hash}.notebook.json"
    persist_job_notebook(path, notebook)

    loaded = load_persisted_notebook(path)

    assert loaded.job_hash == notebook.job_hash
    assert [section.section_id for section in loaded.sections] == [section.section_id for section in notebook.sections]
    assert [section.progress_start_pct for section in loaded.sections] == [
        section.progress_start_pct for section in notebook.sections
    ]
    assert [section.progress_end_pct for section in loaded.sections] == [
        section.progress_end_pct for section in notebook.sections
    ]
    assert loaded.active_section(90.0).section_id == notebook.active_section(90.0).section_id
    assert [note.note_id for note in loaded.global_notes] == [note.note_id for note in notebook.global_notes]
    assert loaded.parser_version == CURRENT_NOTEBOOK_PARSER_VERSION


def test_load_persisted_notebook_accepts_legacy_section_payload_without_progress_windows(tmp_path):
    notebook = build_job_notebook(
        printable=PrintableFile(path="/usb/PRINTS/DEMO.GCODE", display_name="demo.gcode"),
        file_info=None,
        file_text=_SAMPLE_GCODE,
    )
    assert notebook is not None
    path = tmp_path / f"{notebook.job_hash}.notebook.json"
    payload = notebook_to_jsonable(notebook)
    payload["schema_version"] = "1.2"
    for section in payload["sections"]:
        section.pop("progress_start_pct")
        section.pop("progress_end_pct")
    path.write_text(json.dumps(payload), encoding="utf-8")

    loaded = load_persisted_notebook(path)

    assert loaded.job_hash == notebook.job_hash
    assert all(section.progress_start_pct == 0.0 for section in loaded.sections)
    assert all(section.progress_end_pct == 100.0 for section in loaded.sections)


def test_decode_real_benchy_bgcode_fixture_produces_canonical_markers():
    text = decode_bgcode_text(_bgcode_fixture_bytes("benchy_rules_real.bgcode"))

    assert ";LAYER_CHANGE" in text
    assert ";TYPE:" in text
    assert ";Z:" in text
    assert "; filament_type=PLA" in text


def test_decode_real_stringing_bgcode_fixture_produces_canonical_markers():
    text = decode_bgcode_text(_bgcode_fixture_bytes("stringing_v2_real.bgcode"))

    assert ";LAYER_CHANGE" in text
    assert ";TYPE:" in text
    assert ";Z:" in text
    assert "Stringing" not in text or "; filament_type=" in text


def test_decode_bgcode_rejects_truncated_gcde_container():
    try:
        decode_bgcode_text(b"GCDE\x01\x00\x00\x00\x01\x00")
    except BgcodeDecodeError as exc:
        assert "truncated" in str(exc) or "no gcode blocks" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected truncated bgcode to fail loudly")


def test_benchy_golden_grounding_has_sections_and_nonempty_active_notes():
    real_text = normalize_prusa_print_text(
        file_path="/usb/BENCHY~2.BGC",
        raw_bytes=_bgcode_fixture_bytes("benchy_rules_real.bgcode"),
    )
    notebook = build_job_notebook(
        printable=PrintableFile(
            path="/usb/PRINTS/BENCHY~2.BGC",
            display_name="Benchy_Rules_0.4n_0.2mm_PLA_COREONE_14m.bgcode",
            size_bytes=len(_bgcode_fixture_bytes("benchy_rules_real.bgcode")),
        ),
        file_info=None,
        file_text=real_text,
    )
    assert notebook is not None

    section_ids = {section.section_id for section in notebook.sections}
    assert len(notebook.sections) >= 3
    assert notebook.global_notes
    assert notebook.local_notes
    assert all(not note.section_ids for note in notebook.global_notes)
    assert all(set(note.section_ids).issubset(section_ids) for note in notebook.local_notes)

    active = notebook.select_active_notes(50.0, lifecycle="PRINTING", job_active=True)
    assert active.selection_context.current_section_ids
    assert active.global_notes or active.local_notes
    assert any("bridge" in note.reason_tags or "high_flow" in note.reason_tags for note in active.global_notes + active.local_notes)
    assert notebook.source_text_grounded_internal is True


def test_stringing_tower_golden_grounding_has_sections_and_nonempty_active_notes():
    real_text = normalize_prusa_print_text(
        file_path="/usb/STRI~125.BGC",
        raw_bytes=_bgcode_fixture_bytes("stringing_v2_real.bgcode"),
    )
    notebook = build_job_notebook(
        printable=PrintableFile(
            path="/usb/PRINTS/STRINGING~1.BGC",
            display_name="Stringing_v2_Test_mini_0.4n_0.2mm_PLA_COREONE_7m.bgcode",
            size_bytes=len(_bgcode_fixture_bytes("stringing_v2_real.bgcode")),
        ),
        file_info=None,
        file_text=real_text,
    )
    assert notebook is not None

    section_ids = {section.section_id for section in notebook.sections}
    assert len(notebook.sections) >= 3
    assert notebook.global_notes
    assert notebook.local_notes
    assert all(not note.section_ids for note in notebook.global_notes)
    assert all(set(note.section_ids).issubset(section_ids) for note in notebook.local_notes)

    active = notebook.select_active_notes(40.0, lifecycle="PRINTING", job_active=True)
    assert active.selection_context.current_section_ids
    assert active.global_notes or active.local_notes
    assert any(note.suggested_families for note in active.global_notes + active.local_notes)
