; generated by PrusaSlicer
; filament_type = PLA
; nozzle_temperature = 215
; bed_temperature = 60
; layer_height = 0.20
; nozzle_diameter = 0.40
M104 S215
M140 S60
;LAYER_CHANGE
;LAYER:0
;TYPE:External perimeter
G1 X0 Y0 F1200.0
G1 X20 Y0 E0.4
G1 X20 Y20 E0.8
;TYPE:Internal infill
G1 X5 Y5 F1800.0
G1 X15 Y5 E1.0
;LAYER_CHANGE
;LAYER:1
;TYPE:Perimeter
G1 X0 Y0 F1500.0
G1 X20 Y0 E1.2
;TYPE:Bridge infill
G1 X4 Y4 F900.0
G1 X16 Y4 E1.5
;LAYER_CHANGE
;LAYER:2
;TYPE:Solid infill
G1 X3 Y3 F1600.0
G1 X17 Y3 E1.8
